### PR TITLE
REFACTORING from jerbil to mkdocs

### PR DESCRIPTION
**Pull request by wongws11**
Turns out it is very easy to port this from `jerbil` to `mkdocs`. This will put poor jerbil at rest. 

But do we want to? 

Very clearly many pages in this doc are outdated. We will have to edit/ delete many, many paragraphs. That means we will have to review the doc in this repo. Do we have the time? 

## Pro

- No more jerbil
- Deploy the website on Cloud with GitHub action, or even in container
- No more doc website server to maintenance
- A real search function built-in
- Modern UI/UX, our api-doc and doc will look the same

## Con

- All of the outdated docs are now beautifully presented 
- Need to get someone to review and remove outdated contents

Let's talk about it.

### CODE REVIEW

**Comment by craigrobertson0** [comment]
Wing,

If you are talking about building a stand-alone Docker with all of the
documentation there then yep, I'm all in,
So yes, we can maintain and publish it using a GitHubs action to rebuild
the container whenever anything changes or is updated.
Which container are you thinking of, just nginx or something with a bigger
footprint?

Cheers,
Craig

**Comment by thoaid** [comment]
I’d recommend using the same setup we have going for api-doc. A simple
Github actions + Github Pages as the host. No need for docker/nginx.

I’m all in favour of dropping Jerbil completely.

<https://good-loop.com>
Aidan Thomson
System Administrator
+44 (0) 7732 571 280good-loop.com
As featured in AdWeek
<https://www.adweek.com/agencies/ad-tracker-tool-to-improve-advertisers-digital-media-carbon-footprint/>,
Campaign
<https://www.campaignlive.co.uk/article/meet-start-up-helping-nestle-nike-unilever-unite-programmatic-purpose/1722847>,
MediaPost
<https://www.mediapost.com/publications/article/365270/ad-tech-startup-launches-carbon-tag-utilizes-tree.html>,
and The Times
<https://www.thetimes.co.uk/article/rising-stars-the-companies-growing-fast-in-scotland-k37hhdfnp>
.
<https://good-loop.com>

**Comment by thoaid** [comment]
I’d recommend using the same setup we have going for api-doc. A simple
Github actions + Github Pages as the host. No need for docker/nginx.

I’m all in favour of dropping Jerbil completely.


<https://good-loop.com>
Aidan Thomson
System Administrator
+44 (0) 7732 571 280good-loop.com
As featured in AdWeek
<https://www.adweek.com/agencies/ad-tracker-tool-to-improve-advertisers-digital-media-carbon-footprint/>,
Campaign
<https://www.campaignlive.co.uk/article/meet-start-up-helping-nestle-nike-unilever-unite-programmatic-purpose/1722847>,
MediaPost
<https://www.mediapost.com/publications/article/365270/ad-tech-startup-launches-carbon-tag-utilizes-tree.html>,
and The Times
<https://www.thetimes.co.uk/article/rising-stars-the-companies-growing-fast-in-scotland-k37hhdfnp>
.
<https://good-loop.com>

**Comment by wongws11** [comment]
Update from Software Design Meeting:
*Pull down the whole doc.good-loop.com as most contents are now outdated.*

**Pull request merged**
